apiVersion: v1
kind: Pod
metadata:
  name: export-mnist
  namespace: kubeflow-user
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: volumeop-sequential-psxn6-newpvc
  containers:
    - name: task-pv-container
      image: ubuntu:18.04
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
      volumeMounts:
        - mountPath: "/data"
          name: task-pv-storage
