## run
#
# kubectl get viewer -n kubeflow-user-example-com to get latest viewer id
# and replace it with <viewer-name>
#
# kubectl get pvc -n kubeflow-user-example-com | grep volumeop to get pipeline's pvc name
# and replace it with <pvc-claim-name>
#
# then create a view directly by
# kubectl apply -f hack/tensorboard-use-local-volume.yaml


apiVersion: kubeflow.org/v1beta1
kind: Viewer
metadata:
  name: <viewer-name>
  namespace: kubeflow-user-example-com
spec:
  podTemplateSpec:
    spec:
      containers:
      - volumeMounts:
        - mountPath: /data
          name: mypvc
      serviceAccountName: default-editor
      volumes:
      - name: mypvc
        persistentVolumeClaim:
          claimName: <pvc-claim-name>
  tensorboardSpec:
    logDir: /data
    tensorflowImage: footprintai/tensorboard:2.7.0 # see https://github.com/FootprintAI/tensorboardd
  type: tensorboard
